/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsMarblesRouteImport } from './routes/products/marbles'
import { Route as ProductsGranitesRouteImport } from './routes/products/granites'
import { Route as ProductsGranitesSlugRouteImport } from './routes/products/granites.$slug'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsMarblesRoute = ProductsMarblesRouteImport.update({
  id: '/products/marbles',
  path: '/products/marbles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsGranitesRoute = ProductsGranitesRouteImport.update({
  id: '/products/granites',
  path: '/products/granites',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsGranitesSlugRoute = ProductsGranitesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsGranitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products/granites': typeof ProductsGranitesRouteWithChildren
  '/products/marbles': typeof ProductsMarblesRoute
  '/products/': typeof ProductsIndexRoute
  '/products/granites/$slug': typeof ProductsGranitesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products/granites': typeof ProductsGranitesRouteWithChildren
  '/products/marbles': typeof ProductsMarblesRoute
  '/products': typeof ProductsIndexRoute
  '/products/granites/$slug': typeof ProductsGranitesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products/granites': typeof ProductsGranitesRouteWithChildren
  '/products/marbles': typeof ProductsMarblesRoute
  '/products/': typeof ProductsIndexRoute
  '/products/granites/$slug': typeof ProductsGranitesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/products/granites'
    | '/products/marbles'
    | '/products/'
    | '/products/granites/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/products/granites'
    | '/products/marbles'
    | '/products'
    | '/products/granites/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/products/granites'
    | '/products/marbles'
    | '/products/'
    | '/products/granites/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProductsGranitesRoute: typeof ProductsGranitesRouteWithChildren
  ProductsMarblesRoute: typeof ProductsMarblesRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/marbles': {
      id: '/products/marbles'
      path: '/products/marbles'
      fullPath: '/products/marbles'
      preLoaderRoute: typeof ProductsMarblesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/granites': {
      id: '/products/granites'
      path: '/products/granites'
      fullPath: '/products/granites'
      preLoaderRoute: typeof ProductsGranitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/granites/$slug': {
      id: '/products/granites/$slug'
      path: '/$slug'
      fullPath: '/products/granites/$slug'
      preLoaderRoute: typeof ProductsGranitesSlugRouteImport
      parentRoute: typeof ProductsGranitesRoute
    }
  }
}

interface ProductsGranitesRouteChildren {
  ProductsGranitesSlugRoute: typeof ProductsGranitesSlugRoute
}

const ProductsGranitesRouteChildren: ProductsGranitesRouteChildren = {
  ProductsGranitesSlugRoute: ProductsGranitesSlugRoute,
}

const ProductsGranitesRouteWithChildren =
  ProductsGranitesRoute._addFileChildren(ProductsGranitesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProductsGranitesRoute: ProductsGranitesRouteWithChildren,
  ProductsMarblesRoute: ProductsMarblesRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
